[tool.kedro]
package_name = "image_classification_on_cifar10"
project_name = "Image Classification on CIFAR10"
kedro_init_version = "0.18.5"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/image_classification_on_cifar10 -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
